// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Buff/ActiveBuffSource.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Buff {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Buff/ActiveBuffSource.proto</summary>
  public static partial class ActiveBuffSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Buff/ActiveBuffSource.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActiveBuffSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilXVVByb3Rvcy9EYXRhL0J1ZmYvQWN0aXZlQnVmZlNvdXJjZS5wcm90bxIS",
            "V1VQcm90b3MuRGF0YS5CdWZmGi1XVVByb3Rvcy9EYXRhL1ZhdWx0SXRlbUFj",
            "dGl2ZUJ1ZmZTb3VyY2UucHJvdG8aOVdVUHJvdG9zL0RhdGEvUHJvZmVzc2lv",
            "bi9Qcm9mZXNzaW9uQWN0aXZlQnVmZlNvdXJjZS5wcm90bxouV1VQcm90b3Mv",
            "RGF0YS9NYXBBYmlsaXR5QWN0aXZlQnVmZlNvdXJjZS5wcm90byLoAQoQQWN0",
            "aXZlQnVmZlNvdXJjZRI+Cgp2YXVsdF9pdGVtGAEgASgLMiguV1VQcm90b3Mu",
            "RGF0YS5WYXVsdEl0ZW1BY3RpdmVCdWZmU291cmNlSAASSgoKcHJvZmVzc2lv",
            "bhgCIAEoCzI0LldVUHJvdG9zLkRhdGEuUHJvZmVzc2lvbi5Qcm9mZXNzaW9u",
            "QWN0aXZlQnVmZlNvdXJjZUgAEkAKC21hcF9hYmlsaXR5GAMgASgLMikuV1VQ",
            "cm90b3MuRGF0YS5NYXBBYmlsaXR5QWN0aXZlQnVmZlNvdXJjZUgAQgYKBFR5",
            "cGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.VaultItemActiveBuffSourceReflection.Descriptor, global::WUProtos.Data.Profession.ProfessionActiveBuffSourceReflection.Descriptor, global::WUProtos.Data.MapAbilityActiveBuffSourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Buff.ActiveBuffSource), global::WUProtos.Data.Buff.ActiveBuffSource.Parser, new[]{ "VaultItem", "Profession", "MapAbility" }, new[]{ "Type" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ActiveBuffSource : pb::IMessage<ActiveBuffSource> {
    private static readonly pb::MessageParser<ActiveBuffSource> _parser = new pb::MessageParser<ActiveBuffSource>(() => new ActiveBuffSource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActiveBuffSource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Buff.ActiveBuffSourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActiveBuffSource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActiveBuffSource(ActiveBuffSource other) : this() {
      switch (other.TypeCase) {
        case TypeOneofCase.VaultItem:
          VaultItem = other.VaultItem.Clone();
          break;
        case TypeOneofCase.Profession:
          Profession = other.Profession.Clone();
          break;
        case TypeOneofCase.MapAbility:
          MapAbility = other.MapAbility.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActiveBuffSource Clone() {
      return new ActiveBuffSource(this);
    }

    /// <summary>Field number for the "vault_item" field.</summary>
    public const int VaultItemFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.VaultItemActiveBuffSource VaultItem {
      get { return typeCase_ == TypeOneofCase.VaultItem ? (global::WUProtos.Data.VaultItemActiveBuffSource) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.VaultItem;
      }
    }

    /// <summary>Field number for the "profession" field.</summary>
    public const int ProfessionFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Profession.ProfessionActiveBuffSource Profession {
      get { return typeCase_ == TypeOneofCase.Profession ? (global::WUProtos.Data.Profession.ProfessionActiveBuffSource) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.Profession;
      }
    }

    /// <summary>Field number for the "map_ability" field.</summary>
    public const int MapAbilityFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.MapAbilityActiveBuffSource MapAbility {
      get { return typeCase_ == TypeOneofCase.MapAbility ? (global::WUProtos.Data.MapAbilityActiveBuffSource) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.MapAbility;
      }
    }

    private object type_;
    /// <summary>Enum of possible cases for the "Type" oneof.</summary>
    public enum TypeOneofCase {
      None = 0,
      VaultItem = 1,
      Profession = 2,
      MapAbility = 3,
    }
    private TypeOneofCase typeCase_ = TypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TypeOneofCase TypeCase {
      get { return typeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearType() {
      typeCase_ = TypeOneofCase.None;
      type_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActiveBuffSource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActiveBuffSource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(VaultItem, other.VaultItem)) return false;
      if (!object.Equals(Profession, other.Profession)) return false;
      if (!object.Equals(MapAbility, other.MapAbility)) return false;
      if (TypeCase != other.TypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (typeCase_ == TypeOneofCase.VaultItem) hash ^= VaultItem.GetHashCode();
      if (typeCase_ == TypeOneofCase.Profession) hash ^= Profession.GetHashCode();
      if (typeCase_ == TypeOneofCase.MapAbility) hash ^= MapAbility.GetHashCode();
      hash ^= (int) typeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (typeCase_ == TypeOneofCase.VaultItem) {
        output.WriteRawTag(10);
        output.WriteMessage(VaultItem);
      }
      if (typeCase_ == TypeOneofCase.Profession) {
        output.WriteRawTag(18);
        output.WriteMessage(Profession);
      }
      if (typeCase_ == TypeOneofCase.MapAbility) {
        output.WriteRawTag(26);
        output.WriteMessage(MapAbility);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (typeCase_ == TypeOneofCase.VaultItem) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VaultItem);
      }
      if (typeCase_ == TypeOneofCase.Profession) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Profession);
      }
      if (typeCase_ == TypeOneofCase.MapAbility) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MapAbility);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActiveBuffSource other) {
      if (other == null) {
        return;
      }
      switch (other.TypeCase) {
        case TypeOneofCase.VaultItem:
          if (VaultItem == null) {
            VaultItem = new global::WUProtos.Data.VaultItemActiveBuffSource();
          }
          VaultItem.MergeFrom(other.VaultItem);
          break;
        case TypeOneofCase.Profession:
          if (Profession == null) {
            Profession = new global::WUProtos.Data.Profession.ProfessionActiveBuffSource();
          }
          Profession.MergeFrom(other.Profession);
          break;
        case TypeOneofCase.MapAbility:
          if (MapAbility == null) {
            MapAbility = new global::WUProtos.Data.MapAbilityActiveBuffSource();
          }
          MapAbility.MergeFrom(other.MapAbility);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::WUProtos.Data.VaultItemActiveBuffSource subBuilder = new global::WUProtos.Data.VaultItemActiveBuffSource();
            if (typeCase_ == TypeOneofCase.VaultItem) {
              subBuilder.MergeFrom(VaultItem);
            }
            input.ReadMessage(subBuilder);
            VaultItem = subBuilder;
            break;
          }
          case 18: {
            global::WUProtos.Data.Profession.ProfessionActiveBuffSource subBuilder = new global::WUProtos.Data.Profession.ProfessionActiveBuffSource();
            if (typeCase_ == TypeOneofCase.Profession) {
              subBuilder.MergeFrom(Profession);
            }
            input.ReadMessage(subBuilder);
            Profession = subBuilder;
            break;
          }
          case 26: {
            global::WUProtos.Data.MapAbilityActiveBuffSource subBuilder = new global::WUProtos.Data.MapAbilityActiveBuffSource();
            if (typeCase_ == TypeOneofCase.MapAbility) {
              subBuilder.MergeFrom(MapAbility);
            }
            input.ReadMessage(subBuilder);
            MapAbility = subBuilder;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
