// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Responses/BuyPotionIngredientsResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Responses/BuyPotionIngredientsResponse.proto</summary>
  public static partial class BuyPotionIngredientsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Responses/BuyPotionIngredientsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BuyPotionIngredientsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkBXVVByb3Rvcy9OZXR3b3JraW5nL1Jlc3BvbnNlcy9CdXlQb3Rpb25Jbmdy",
            "ZWRpZW50c1Jlc3BvbnNlLnByb3RvEh1XVVByb3Rvcy5OZXR3b3JraW5nLlJl",
            "c3BvbnNlcxonV1VQcm90b3MvRGF0YS9Mb290L0xvb3RDb2xsZWN0aW9uLnBy",
            "b3RvIq8CChxCdXlQb3Rpb25JbmdyZWRpZW50c1Jlc3BvbnNlElIKBnN0YXR1",
            "cxgBIAEoDjJCLldVUHJvdG9zLk5ldHdvcmtpbmcuUmVzcG9uc2VzLkJ1eVBv",
            "dGlvbkluZ3JlZGllbnRzUmVzcG9uc2UuU3RhdHVzEjMKB3Jld2FyZHMYAiAB",
            "KAsyIi5XVVByb3Rvcy5EYXRhLkxvb3QuTG9vdENvbGxlY3Rpb24ihQEKBlN0",
            "YXR1cxILCgdVTktOT1dOEAASCQoFRVJST1IQARIWChJQQUNLX05PVF9BVkFJ",
            "TEFCTEUQAhIWChJJTlNVRkZJQ0lFTlRfRlVORFMQAxIVChFBTFJFQURZX1BV",
            "UkNIQVNFRBAEEgsKB1NVQ0NFU1MQBRIPCgtBVF9JVEVNX0NBUBAGYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.Loot.LootCollectionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Responses.BuyPotionIngredientsResponse), global::WUProtos.Networking.Responses.BuyPotionIngredientsResponse.Parser, new[]{ "Status", "Rewards" }, null, new[]{ typeof(global::WUProtos.Networking.Responses.BuyPotionIngredientsResponse.Types.Status) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BuyPotionIngredientsResponse : pb::IMessage<BuyPotionIngredientsResponse> {
    private static readonly pb::MessageParser<BuyPotionIngredientsResponse> _parser = new pb::MessageParser<BuyPotionIngredientsResponse>(() => new BuyPotionIngredientsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BuyPotionIngredientsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Responses.BuyPotionIngredientsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuyPotionIngredientsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuyPotionIngredientsResponse(BuyPotionIngredientsResponse other) : this() {
      status_ = other.status_;
      rewards_ = other.rewards_ != null ? other.rewards_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BuyPotionIngredientsResponse Clone() {
      return new BuyPotionIngredientsResponse(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::WUProtos.Networking.Responses.BuyPotionIngredientsResponse.Types.Status status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Networking.Responses.BuyPotionIngredientsResponse.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "rewards" field.</summary>
    public const int RewardsFieldNumber = 2;
    private global::WUProtos.Data.Loot.LootCollection rewards_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Loot.LootCollection Rewards {
      get { return rewards_; }
      set {
        rewards_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BuyPotionIngredientsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BuyPotionIngredientsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (!object.Equals(Rewards, other.Rewards)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (rewards_ != null) hash ^= Rewards.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (rewards_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Rewards);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (rewards_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rewards);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BuyPotionIngredientsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.rewards_ != null) {
        if (rewards_ == null) {
          Rewards = new global::WUProtos.Data.Loot.LootCollection();
        }
        Rewards.MergeFrom(other.Rewards);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::WUProtos.Networking.Responses.BuyPotionIngredientsResponse.Types.Status) input.ReadEnum();
            break;
          }
          case 18: {
            if (rewards_ == null) {
              Rewards = new global::WUProtos.Data.Loot.LootCollection();
            }
            input.ReadMessage(Rewards);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the BuyPotionIngredientsResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("PACK_NOT_AVAILABLE")] PackNotAvailable = 2,
        [pbr::OriginalName("INSUFFICIENT_FUNDS")] InsufficientFunds = 3,
        [pbr::OriginalName("ALREADY_PURCHASED")] AlreadyPurchased = 4,
        [pbr::OriginalName("SUCCESS")] Success = 5,
        [pbr::OriginalName("AT_ITEM_CAP")] AtItemCap = 6,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
