// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Responses/DbgUpdateInventoryResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Responses/DbgUpdateInventoryResponse.proto</summary>
  public static partial class DbgUpdateInventoryResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Responses/DbgUpdateInventoryResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DbgUpdateInventoryResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj5XVVByb3Rvcy9OZXR3b3JraW5nL1Jlc3BvbnNlcy9EYmdVcGRhdGVJbnZl",
            "bnRvcnlSZXNwb25zZS5wcm90bxIdV1VQcm90b3MuTmV0d29ya2luZy5SZXNw",
            "b25zZXMaJVdVUHJvdG9zL0RhdGEvQXRsYXNJbnZlbnRvcnlLZXkucHJvdG8i",
            "3QEKIERiZ1VwZGF0ZVBsYXllckludmVudG9yeVJlc3BvbnNlEhIKCnN1Y2Nl",
            "c3NmdWwYASABKAgSNAoKYWRkZWRfa2V5cxgCIAMoCzIgLldVUHJvdG9zLkRh",
            "dGEuQXRsYXNJbnZlbnRvcnlLZXkSNwoNcmVwbGFjZWRfa2V5cxgDIAMoCzIg",
            "LldVUHJvdG9zLkRhdGEuQXRsYXNJbnZlbnRvcnlLZXkSNgoMZGVsZXRlZF9r",
            "ZXlzGAQgAygLMiAuV1VQcm90b3MuRGF0YS5BdGxhc0ludmVudG9yeUtleWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.AtlasInventoryKeyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Responses.DbgUpdatePlayerInventoryResponse), global::WUProtos.Networking.Responses.DbgUpdatePlayerInventoryResponse.Parser, new[]{ "Successful", "AddedKeys", "ReplacedKeys", "DeletedKeys" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DbgUpdatePlayerInventoryResponse : pb::IMessage<DbgUpdatePlayerInventoryResponse> {
    private static readonly pb::MessageParser<DbgUpdatePlayerInventoryResponse> _parser = new pb::MessageParser<DbgUpdatePlayerInventoryResponse>(() => new DbgUpdatePlayerInventoryResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DbgUpdatePlayerInventoryResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Responses.DbgUpdateInventoryResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgUpdatePlayerInventoryResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgUpdatePlayerInventoryResponse(DbgUpdatePlayerInventoryResponse other) : this() {
      successful_ = other.successful_;
      addedKeys_ = other.addedKeys_.Clone();
      replacedKeys_ = other.replacedKeys_.Clone();
      deletedKeys_ = other.deletedKeys_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DbgUpdatePlayerInventoryResponse Clone() {
      return new DbgUpdatePlayerInventoryResponse(this);
    }

    /// <summary>Field number for the "successful" field.</summary>
    public const int SuccessfulFieldNumber = 1;
    private bool successful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Successful {
      get { return successful_; }
      set {
        successful_ = value;
      }
    }

    /// <summary>Field number for the "added_keys" field.</summary>
    public const int AddedKeysFieldNumber = 2;
    private static readonly pb::FieldCodec<global::WUProtos.Data.AtlasInventoryKey> _repeated_addedKeys_codec
        = pb::FieldCodec.ForMessage(18, global::WUProtos.Data.AtlasInventoryKey.Parser);
    private readonly pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey> addedKeys_ = new pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey> AddedKeys {
      get { return addedKeys_; }
    }

    /// <summary>Field number for the "replaced_keys" field.</summary>
    public const int ReplacedKeysFieldNumber = 3;
    private static readonly pb::FieldCodec<global::WUProtos.Data.AtlasInventoryKey> _repeated_replacedKeys_codec
        = pb::FieldCodec.ForMessage(26, global::WUProtos.Data.AtlasInventoryKey.Parser);
    private readonly pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey> replacedKeys_ = new pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey> ReplacedKeys {
      get { return replacedKeys_; }
    }

    /// <summary>Field number for the "deleted_keys" field.</summary>
    public const int DeletedKeysFieldNumber = 4;
    private static readonly pb::FieldCodec<global::WUProtos.Data.AtlasInventoryKey> _repeated_deletedKeys_codec
        = pb::FieldCodec.ForMessage(34, global::WUProtos.Data.AtlasInventoryKey.Parser);
    private readonly pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey> deletedKeys_ = new pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WUProtos.Data.AtlasInventoryKey> DeletedKeys {
      get { return deletedKeys_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DbgUpdatePlayerInventoryResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DbgUpdatePlayerInventoryResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Successful != other.Successful) return false;
      if(!addedKeys_.Equals(other.addedKeys_)) return false;
      if(!replacedKeys_.Equals(other.replacedKeys_)) return false;
      if(!deletedKeys_.Equals(other.deletedKeys_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Successful != false) hash ^= Successful.GetHashCode();
      hash ^= addedKeys_.GetHashCode();
      hash ^= replacedKeys_.GetHashCode();
      hash ^= deletedKeys_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Successful != false) {
        output.WriteRawTag(8);
        output.WriteBool(Successful);
      }
      addedKeys_.WriteTo(output, _repeated_addedKeys_codec);
      replacedKeys_.WriteTo(output, _repeated_replacedKeys_codec);
      deletedKeys_.WriteTo(output, _repeated_deletedKeys_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Successful != false) {
        size += 1 + 1;
      }
      size += addedKeys_.CalculateSize(_repeated_addedKeys_codec);
      size += replacedKeys_.CalculateSize(_repeated_replacedKeys_codec);
      size += deletedKeys_.CalculateSize(_repeated_deletedKeys_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DbgUpdatePlayerInventoryResponse other) {
      if (other == null) {
        return;
      }
      if (other.Successful != false) {
        Successful = other.Successful;
      }
      addedKeys_.Add(other.addedKeys_);
      replacedKeys_.Add(other.replacedKeys_);
      deletedKeys_.Add(other.deletedKeys_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Successful = input.ReadBool();
            break;
          }
          case 18: {
            addedKeys_.AddEntriesFrom(input, _repeated_addedKeys_codec);
            break;
          }
          case 26: {
            replacedKeys_.AddEntriesFrom(input, _repeated_replacedKeys_codec);
            break;
          }
          case 34: {
            deletedKeys_.AddEntriesFrom(input, _repeated_deletedKeys_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
