// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Networking/Responses/GetOutpostDetailsResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from WUProtos/Networking/Responses/GetOutpostDetailsResponse.proto</summary>
  public static partial class GetOutpostDetailsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Networking/Responses/GetOutpostDetailsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetOutpostDetailsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj1XVVByb3Rvcy9OZXR3b3JraW5nL1Jlc3BvbnNlcy9HZXRPdXRwb3N0RGV0",
            "YWlsc1Jlc3BvbnNlLnByb3RvEh1XVVByb3Rvcy5OZXR3b3JraW5nLlJlc3Bv",
            "bnNlcxofV1VQcm90b3MvRGF0YS9PdXRwb3N0TWVudS5wcm90bxoeV1VQcm90",
            "b3MvRGF0YS9Qb2lEZXRhaWxzLnByb3RvGiVXVVByb3Rvcy9FbnVtcy9Qb2lB",
            "Y2Nlc3NpYmlsaXR5LnByb3RvIuIBChlHZXRPdXRwb3N0RGV0YWlsc1Jlc3Bv",
            "bnNlEhIKCmltYWdlX3VybHMYASADKAkSMAoMY3VycmVudF9tZW51GAIgASgL",
            "MhouV1VQcm90b3MuRGF0YS5PdXRwb3N0TWVudRISCgpwYXJ0bmVyX2lkGAMg",
            "ASgJEi4KC3BvaV9kZXRhaWxzGAQgASgLMhkuV1VQcm90b3MuRGF0YS5Qb2lE",
            "ZXRhaWxzEjsKEXBvaV9hY2Nlc3NpYmlsaXR5GAUgASgOMiAuV1VQcm90b3Mu",
            "RW51bXMuUG9pQWNjZXNzaWJpbGl0eWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.OutpostMenuReflection.Descriptor, global::WUProtos.Data.PoiDetailsReflection.Descriptor, global::WUProtos.Enums.PoiAccessibilityReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Networking.Responses.GetOutpostDetailsResponse), global::WUProtos.Networking.Responses.GetOutpostDetailsResponse.Parser, new[]{ "ImageUrls", "CurrentMenu", "PartnerId", "PoiDetails", "PoiAccessibility" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetOutpostDetailsResponse : pb::IMessage<GetOutpostDetailsResponse> {
    private static readonly pb::MessageParser<GetOutpostDetailsResponse> _parser = new pb::MessageParser<GetOutpostDetailsResponse>(() => new GetOutpostDetailsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetOutpostDetailsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Networking.Responses.GetOutpostDetailsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOutpostDetailsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOutpostDetailsResponse(GetOutpostDetailsResponse other) : this() {
      imageUrls_ = other.imageUrls_.Clone();
      currentMenu_ = other.currentMenu_ != null ? other.currentMenu_.Clone() : null;
      partnerId_ = other.partnerId_;
      poiDetails_ = other.poiDetails_ != null ? other.poiDetails_.Clone() : null;
      poiAccessibility_ = other.poiAccessibility_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetOutpostDetailsResponse Clone() {
      return new GetOutpostDetailsResponse(this);
    }

    /// <summary>Field number for the "image_urls" field.</summary>
    public const int ImageUrlsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_imageUrls_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> imageUrls_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ImageUrls {
      get { return imageUrls_; }
    }

    /// <summary>Field number for the "current_menu" field.</summary>
    public const int CurrentMenuFieldNumber = 2;
    private global::WUProtos.Data.OutpostMenu currentMenu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.OutpostMenu CurrentMenu {
      get { return currentMenu_; }
      set {
        currentMenu_ = value;
      }
    }

    /// <summary>Field number for the "partner_id" field.</summary>
    public const int PartnerIdFieldNumber = 3;
    private string partnerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PartnerId {
      get { return partnerId_; }
      set {
        partnerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "poi_details" field.</summary>
    public const int PoiDetailsFieldNumber = 4;
    private global::WUProtos.Data.PoiDetails poiDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.PoiDetails PoiDetails {
      get { return poiDetails_; }
      set {
        poiDetails_ = value;
      }
    }

    /// <summary>Field number for the "poi_accessibility" field.</summary>
    public const int PoiAccessibilityFieldNumber = 5;
    private global::WUProtos.Enums.PoiAccessibility poiAccessibility_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Enums.PoiAccessibility PoiAccessibility {
      get { return poiAccessibility_; }
      set {
        poiAccessibility_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetOutpostDetailsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetOutpostDetailsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!imageUrls_.Equals(other.imageUrls_)) return false;
      if (!object.Equals(CurrentMenu, other.CurrentMenu)) return false;
      if (PartnerId != other.PartnerId) return false;
      if (!object.Equals(PoiDetails, other.PoiDetails)) return false;
      if (PoiAccessibility != other.PoiAccessibility) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= imageUrls_.GetHashCode();
      if (currentMenu_ != null) hash ^= CurrentMenu.GetHashCode();
      if (PartnerId.Length != 0) hash ^= PartnerId.GetHashCode();
      if (poiDetails_ != null) hash ^= PoiDetails.GetHashCode();
      if (PoiAccessibility != 0) hash ^= PoiAccessibility.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      imageUrls_.WriteTo(output, _repeated_imageUrls_codec);
      if (currentMenu_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CurrentMenu);
      }
      if (PartnerId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PartnerId);
      }
      if (poiDetails_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(PoiDetails);
      }
      if (PoiAccessibility != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) PoiAccessibility);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += imageUrls_.CalculateSize(_repeated_imageUrls_codec);
      if (currentMenu_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CurrentMenu);
      }
      if (PartnerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartnerId);
      }
      if (poiDetails_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PoiDetails);
      }
      if (PoiAccessibility != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PoiAccessibility);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetOutpostDetailsResponse other) {
      if (other == null) {
        return;
      }
      imageUrls_.Add(other.imageUrls_);
      if (other.currentMenu_ != null) {
        if (currentMenu_ == null) {
          CurrentMenu = new global::WUProtos.Data.OutpostMenu();
        }
        CurrentMenu.MergeFrom(other.CurrentMenu);
      }
      if (other.PartnerId.Length != 0) {
        PartnerId = other.PartnerId;
      }
      if (other.poiDetails_ != null) {
        if (poiDetails_ == null) {
          PoiDetails = new global::WUProtos.Data.PoiDetails();
        }
        PoiDetails.MergeFrom(other.PoiDetails);
      }
      if (other.PoiAccessibility != 0) {
        PoiAccessibility = other.PoiAccessibility;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            imageUrls_.AddEntriesFrom(input, _repeated_imageUrls_codec);
            break;
          }
          case 18: {
            if (currentMenu_ == null) {
              CurrentMenu = new global::WUProtos.Data.OutpostMenu();
            }
            input.ReadMessage(CurrentMenu);
            break;
          }
          case 26: {
            PartnerId = input.ReadString();
            break;
          }
          case 34: {
            if (poiDetails_ == null) {
              PoiDetails = new global::WUProtos.Data.PoiDetails();
            }
            input.ReadMessage(PoiDetails);
            break;
          }
          case 40: {
            PoiAccessibility = (global::WUProtos.Enums.PoiAccessibility) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
