// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Telemetry/PlatformDataId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Telemetry {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Telemetry/PlatformDataId.proto</summary>
  public static partial class PlatformDataIdReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Telemetry/PlatformDataId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlatformDataIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixXVVByb3Rvcy9EYXRhL1RlbGVtZXRyeS9QbGF0Zm9ybURhdGFJZC5wcm90",
            "bxIXV1VQcm90b3MuRGF0YS5UZWxlbWV0cnkaL1dVUHJvdG9zL0RhdGEvVGVs",
            "ZW1ldHJ5L1RlbGVtZXRyeURvbWFpbklkLnByb3RvIm8KDlBsYXRmb3JtRGF0",
            "YUlkEhQKDHRlbGVtZXRyeV9pZBgBIAEoBRJHChN0ZWxlbWV0cnlfZG9tYWlu",
            "X2lkGAIgASgOMiouV1VQcm90b3MuRGF0YS5UZWxlbWV0cnkuVGVsZW1ldHJ5",
            "RG9tYWluSWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.Telemetry.TelemetryDomainIdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Telemetry.PlatformDataId), global::WUProtos.Data.Telemetry.PlatformDataId.Parser, new[]{ "TelemetryId", "TelemetryDomainId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlatformDataId : pb::IMessage<PlatformDataId> {
    private static readonly pb::MessageParser<PlatformDataId> _parser = new pb::MessageParser<PlatformDataId>(() => new PlatformDataId());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlatformDataId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Telemetry.PlatformDataIdReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformDataId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformDataId(PlatformDataId other) : this() {
      telemetryId_ = other.telemetryId_;
      telemetryDomainId_ = other.telemetryDomainId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlatformDataId Clone() {
      return new PlatformDataId(this);
    }

    /// <summary>Field number for the "telemetry_id" field.</summary>
    public const int TelemetryIdFieldNumber = 1;
    private int telemetryId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TelemetryId {
      get { return telemetryId_; }
      set {
        telemetryId_ = value;
      }
    }

    /// <summary>Field number for the "telemetry_domain_id" field.</summary>
    public const int TelemetryDomainIdFieldNumber = 2;
    private global::WUProtos.Data.Telemetry.TelemetryDomainId telemetryDomainId_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Telemetry.TelemetryDomainId TelemetryDomainId {
      get { return telemetryDomainId_; }
      set {
        telemetryDomainId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlatformDataId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlatformDataId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TelemetryId != other.TelemetryId) return false;
      if (TelemetryDomainId != other.TelemetryDomainId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TelemetryId != 0) hash ^= TelemetryId.GetHashCode();
      if (TelemetryDomainId != 0) hash ^= TelemetryDomainId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TelemetryId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TelemetryId);
      }
      if (TelemetryDomainId != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) TelemetryDomainId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TelemetryId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TelemetryId);
      }
      if (TelemetryDomainId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TelemetryDomainId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlatformDataId other) {
      if (other == null) {
        return;
      }
      if (other.TelemetryId != 0) {
        TelemetryId = other.TelemetryId;
      }
      if (other.TelemetryDomainId != 0) {
        TelemetryDomainId = other.TelemetryDomainId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TelemetryId = input.ReadInt32();
            break;
          }
          case 16: {
            TelemetryDomainId = (global::WUProtos.Data.Telemetry.TelemetryDomainId) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
