// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/CategoryRandomize.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/CategoryRandomize.proto</summary>
  public static partial class CategoryRandomizeReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/CategoryRandomize.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CategoryRandomizeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZXVVByb3Rvcy9FbnVtcy9DYXRlZ29yeVJhbmRvbWl6ZS5wcm90bxIOV1VQ",
            "cm90b3MuRW51bXMqYQoRQ2F0ZWdvcnlSYW5kb21pemUSHAoYQ0FURUdPUllf",
            "UkFORE9NSVpFX1VOU0VUEAASEgoOUkFORE9NSVpFX0xFTlMQARIaChZSQU5E",
            "T01JWkVfRklMVEVSX0ZSQU1FEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.CategoryRandomize), }, null));
    }
    #endregion

  }
  #region Enums
  public enum CategoryRandomize {
    [pbr::OriginalName("CATEGORY_RANDOMIZE_UNSET")] Unset = 0,
    [pbr::OriginalName("RANDOMIZE_LENS")] RandomizeLens = 1,
    [pbr::OriginalName("RANDOMIZE_FILTER_FRAME")] RandomizeFilterFrame = 2,
  }

  #endregion

}

#endregion Designer generated code
