// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Enums/ProfileTabSource.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Enums {

  /// <summary>Holder for reflection information generated from WUProtos/Enums/ProfileTabSource.proto</summary>
  public static partial class ProfileTabSourceReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Enums/ProfileTabSource.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProfileTabSourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVXVVByb3Rvcy9FbnVtcy9Qcm9maWxlVGFiU291cmNlLnByb3RvEg5XVVBy",
            "b3Rvcy5FbnVtcyp3ChBQcm9maWxlVGFiU291cmNlEhwKGFBST0ZJTEVfVEFC",
            "X1NPVVJDRV9VTlNFVBAAEgsKB1RBQl9ORVcQARISCg5UQUJfTEFTVF9QSE9U",
            "TxACEhMKD1RBQl9TVE9DS19QSE9UTxADEg8KC1RBQl9HQUxMRVJZEARiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::WUProtos.Enums.ProfileTabSource), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ProfileTabSource {
    [pbr::OriginalName("PROFILE_TAB_SOURCE_UNSET")] Unset = 0,
    [pbr::OriginalName("TAB_NEW")] TabNew = 1,
    [pbr::OriginalName("TAB_LAST_PHOTO")] TabLastPhoto = 2,
    [pbr::OriginalName("TAB_STOCK_PHOTO")] TabStockPhoto = 3,
    [pbr::OriginalName("TAB_GALLERY")] TabGallery = 4,
  }

  #endregion

}

#endregion Designer generated code
