// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Client/ClientVaultItem.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Client {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Client/ClientVaultItem.proto</summary>
  public static partial class ClientVaultItemReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Client/ClientVaultItem.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientVaultItemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipXVVByb3Rvcy9EYXRhL0NsaWVudC9DbGllbnRWYXVsdEl0ZW0ucHJvdG8S",
            "FFdVUHJvdG9zLkRhdGEuQ2xpZW50GhlXVVByb3Rvcy9EYXRhL0NvbG9yLnBy",
            "b3RvGh9XVVByb3Rvcy9EYXRhL1NvdW5kQ29uZmlnLnByb3RvIvkCCg9DbGll",
            "bnRWYXVsdEl0ZW0SCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIMCgRpY29u",
            "GAMgASgJEg4KBnByZWZhYhgEIAEoCRIOCgZyYXJpdHkYBSABKAMSEwoLZGVz",
            "Y3JpcHRpb24YBiABKAkSHwoXc2hvd19pbl92YXVsdF9pdGVtX21lbnUYCCAB",
            "KAgSEQoJZGVsZXRhYmxlGAkgASgIEhwKFHNob3dfaW5fcmV3YXJkc19mbG93",
            "GAogASgIEiMKBWNvbG9yGAsgASgLMhQuV1VQcm90b3MuRGF0YS5Db2xvchIS",
            "CgpiYWNrZ3JvdW5kGAwgASgJEhAKCG9yZGVyaW5nGA0gASgFEjAKDHJld2Fy",
            "ZF9zb3VuZBgOIAEoCzIaLldVUHJvdG9zLkRhdGEuU291bmRDb25maWcSHQoV",
            "cmV3YXJkX3NvdW5kX3ByaW9yaXR5GA8gASgFEhsKE3NwaW5lX2FuaW1hdGVk",
            "X2ljb24YECABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.ColorReflection.Descriptor, global::WUProtos.Data.SoundConfigReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Client.ClientVaultItem), global::WUProtos.Data.Client.ClientVaultItem.Parser, new[]{ "Id", "Name", "Icon", "Prefab", "Rarity", "Description", "ShowInVaultItemMenu", "Deletable", "ShowInRewardsFlow", "Color", "Background", "Ordering", "RewardSound", "RewardSoundPriority", "SpineAnimatedIcon" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientVaultItem : pb::IMessage<ClientVaultItem> {
    private static readonly pb::MessageParser<ClientVaultItem> _parser = new pb::MessageParser<ClientVaultItem>(() => new ClientVaultItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientVaultItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Client.ClientVaultItemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientVaultItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientVaultItem(ClientVaultItem other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      icon_ = other.icon_;
      prefab_ = other.prefab_;
      rarity_ = other.rarity_;
      description_ = other.description_;
      showInVaultItemMenu_ = other.showInVaultItemMenu_;
      deletable_ = other.deletable_;
      showInRewardsFlow_ = other.showInRewardsFlow_;
      color_ = other.color_ != null ? other.color_.Clone() : null;
      background_ = other.background_;
      ordering_ = other.ordering_;
      rewardSound_ = other.rewardSound_ != null ? other.rewardSound_.Clone() : null;
      rewardSoundPriority_ = other.rewardSoundPriority_;
      spineAnimatedIcon_ = other.spineAnimatedIcon_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientVaultItem Clone() {
      return new ClientVaultItem(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 3;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefab" field.</summary>
    public const int PrefabFieldNumber = 4;
    private string prefab_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Prefab {
      get { return prefab_; }
      set {
        prefab_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rarity" field.</summary>
    public const int RarityFieldNumber = 5;
    private long rarity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Rarity {
      get { return rarity_; }
      set {
        rarity_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 6;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "show_in_vault_item_menu" field.</summary>
    public const int ShowInVaultItemMenuFieldNumber = 8;
    private bool showInVaultItemMenu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ShowInVaultItemMenu {
      get { return showInVaultItemMenu_; }
      set {
        showInVaultItemMenu_ = value;
      }
    }

    /// <summary>Field number for the "deletable" field.</summary>
    public const int DeletableFieldNumber = 9;
    private bool deletable_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Deletable {
      get { return deletable_; }
      set {
        deletable_ = value;
      }
    }

    /// <summary>Field number for the "show_in_rewards_flow" field.</summary>
    public const int ShowInRewardsFlowFieldNumber = 10;
    private bool showInRewardsFlow_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool ShowInRewardsFlow {
      get { return showInRewardsFlow_; }
      set {
        showInRewardsFlow_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 11;
    private global::WUProtos.Data.Color color_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Color Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "background" field.</summary>
    public const int BackgroundFieldNumber = 12;
    private string background_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Background {
      get { return background_; }
      set {
        background_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ordering" field.</summary>
    public const int OrderingFieldNumber = 13;
    private int ordering_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Ordering {
      get { return ordering_; }
      set {
        ordering_ = value;
      }
    }

    /// <summary>Field number for the "reward_sound" field.</summary>
    public const int RewardSoundFieldNumber = 14;
    private global::WUProtos.Data.SoundConfig rewardSound_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.SoundConfig RewardSound {
      get { return rewardSound_; }
      set {
        rewardSound_ = value;
      }
    }

    /// <summary>Field number for the "reward_sound_priority" field.</summary>
    public const int RewardSoundPriorityFieldNumber = 15;
    private int rewardSoundPriority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RewardSoundPriority {
      get { return rewardSoundPriority_; }
      set {
        rewardSoundPriority_ = value;
      }
    }

    /// <summary>Field number for the "spine_animated_icon" field.</summary>
    public const int SpineAnimatedIconFieldNumber = 16;
    private string spineAnimatedIcon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SpineAnimatedIcon {
      get { return spineAnimatedIcon_; }
      set {
        spineAnimatedIcon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientVaultItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientVaultItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Icon != other.Icon) return false;
      if (Prefab != other.Prefab) return false;
      if (Rarity != other.Rarity) return false;
      if (Description != other.Description) return false;
      if (ShowInVaultItemMenu != other.ShowInVaultItemMenu) return false;
      if (Deletable != other.Deletable) return false;
      if (ShowInRewardsFlow != other.ShowInRewardsFlow) return false;
      if (!object.Equals(Color, other.Color)) return false;
      if (Background != other.Background) return false;
      if (Ordering != other.Ordering) return false;
      if (!object.Equals(RewardSound, other.RewardSound)) return false;
      if (RewardSoundPriority != other.RewardSoundPriority) return false;
      if (SpineAnimatedIcon != other.SpineAnimatedIcon) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Icon.Length != 0) hash ^= Icon.GetHashCode();
      if (Prefab.Length != 0) hash ^= Prefab.GetHashCode();
      if (Rarity != 0L) hash ^= Rarity.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (ShowInVaultItemMenu != false) hash ^= ShowInVaultItemMenu.GetHashCode();
      if (Deletable != false) hash ^= Deletable.GetHashCode();
      if (ShowInRewardsFlow != false) hash ^= ShowInRewardsFlow.GetHashCode();
      if (color_ != null) hash ^= Color.GetHashCode();
      if (Background.Length != 0) hash ^= Background.GetHashCode();
      if (Ordering != 0) hash ^= Ordering.GetHashCode();
      if (rewardSound_ != null) hash ^= RewardSound.GetHashCode();
      if (RewardSoundPriority != 0) hash ^= RewardSoundPriority.GetHashCode();
      if (SpineAnimatedIcon.Length != 0) hash ^= SpineAnimatedIcon.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Icon);
      }
      if (Prefab.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Prefab);
      }
      if (Rarity != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Rarity);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Description);
      }
      if (ShowInVaultItemMenu != false) {
        output.WriteRawTag(64);
        output.WriteBool(ShowInVaultItemMenu);
      }
      if (Deletable != false) {
        output.WriteRawTag(72);
        output.WriteBool(Deletable);
      }
      if (ShowInRewardsFlow != false) {
        output.WriteRawTag(80);
        output.WriteBool(ShowInRewardsFlow);
      }
      if (color_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Color);
      }
      if (Background.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Background);
      }
      if (Ordering != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Ordering);
      }
      if (rewardSound_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(RewardSound);
      }
      if (RewardSoundPriority != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(RewardSoundPriority);
      }
      if (SpineAnimatedIcon.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(SpineAnimatedIcon);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (Prefab.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prefab);
      }
      if (Rarity != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Rarity);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (ShowInVaultItemMenu != false) {
        size += 1 + 1;
      }
      if (Deletable != false) {
        size += 1 + 1;
      }
      if (ShowInRewardsFlow != false) {
        size += 1 + 1;
      }
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (Background.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Background);
      }
      if (Ordering != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Ordering);
      }
      if (rewardSound_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RewardSound);
      }
      if (RewardSoundPriority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RewardSoundPriority);
      }
      if (SpineAnimatedIcon.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SpineAnimatedIcon);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientVaultItem other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Icon.Length != 0) {
        Icon = other.Icon;
      }
      if (other.Prefab.Length != 0) {
        Prefab = other.Prefab;
      }
      if (other.Rarity != 0L) {
        Rarity = other.Rarity;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.ShowInVaultItemMenu != false) {
        ShowInVaultItemMenu = other.ShowInVaultItemMenu;
      }
      if (other.Deletable != false) {
        Deletable = other.Deletable;
      }
      if (other.ShowInRewardsFlow != false) {
        ShowInRewardsFlow = other.ShowInRewardsFlow;
      }
      if (other.color_ != null) {
        if (color_ == null) {
          Color = new global::WUProtos.Data.Color();
        }
        Color.MergeFrom(other.Color);
      }
      if (other.Background.Length != 0) {
        Background = other.Background;
      }
      if (other.Ordering != 0) {
        Ordering = other.Ordering;
      }
      if (other.rewardSound_ != null) {
        if (rewardSound_ == null) {
          RewardSound = new global::WUProtos.Data.SoundConfig();
        }
        RewardSound.MergeFrom(other.RewardSound);
      }
      if (other.RewardSoundPriority != 0) {
        RewardSoundPriority = other.RewardSoundPriority;
      }
      if (other.SpineAnimatedIcon.Length != 0) {
        SpineAnimatedIcon = other.SpineAnimatedIcon;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Icon = input.ReadString();
            break;
          }
          case 34: {
            Prefab = input.ReadString();
            break;
          }
          case 40: {
            Rarity = input.ReadInt64();
            break;
          }
          case 50: {
            Description = input.ReadString();
            break;
          }
          case 64: {
            ShowInVaultItemMenu = input.ReadBool();
            break;
          }
          case 72: {
            Deletable = input.ReadBool();
            break;
          }
          case 80: {
            ShowInRewardsFlow = input.ReadBool();
            break;
          }
          case 90: {
            if (color_ == null) {
              Color = new global::WUProtos.Data.Color();
            }
            input.ReadMessage(Color);
            break;
          }
          case 98: {
            Background = input.ReadString();
            break;
          }
          case 104: {
            Ordering = input.ReadInt32();
            break;
          }
          case 114: {
            if (rewardSound_ == null) {
              RewardSound = new global::WUProtos.Data.SoundConfig();
            }
            input.ReadMessage(RewardSound);
            break;
          }
          case 120: {
            RewardSoundPriority = input.ReadInt32();
            break;
          }
          case 130: {
            SpineAnimatedIcon = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
