// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Client/ClientCombatState.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Client {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Client/ClientCombatState.proto</summary>
  public static partial class ClientCombatStateReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Client/ClientCombatState.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientCombatStateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CixXVVByb3Rvcy9EYXRhL0NsaWVudC9DbGllbnRDb21iYXRTdGF0ZS5wcm90",
            "bxIUV1VQcm90b3MuRGF0YS5DbGllbnQaL1dVUHJvdG9zL0RhdGEvQ2xpZW50",
            "L0NsaWVudENvbWJhdE1vdmVUeXBlLnByb3RvIlcKEUNsaWVudENvbWJhdFN0",
            "YXRlEkIKDnBvc3NpYmxlX21vdmVzGAEgAygLMiouV1VQcm90b3MuRGF0YS5D",
            "bGllbnQuQ2xpZW50Q29tYmF0TW92ZVR5cGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.Client.ClientCombatMoveTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Client.ClientCombatState), global::WUProtos.Data.Client.ClientCombatState.Parser, new[]{ "PossibleMoves" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientCombatState : pb::IMessage<ClientCombatState> {
    private static readonly pb::MessageParser<ClientCombatState> _parser = new pb::MessageParser<ClientCombatState>(() => new ClientCombatState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientCombatState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Client.ClientCombatStateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientCombatState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientCombatState(ClientCombatState other) : this() {
      possibleMoves_ = other.possibleMoves_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientCombatState Clone() {
      return new ClientCombatState(this);
    }

    /// <summary>Field number for the "possible_moves" field.</summary>
    public const int PossibleMovesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::WUProtos.Data.Client.ClientCombatMoveType> _repeated_possibleMoves_codec
        = pb::FieldCodec.ForMessage(10, global::WUProtos.Data.Client.ClientCombatMoveType.Parser);
    private readonly pbc::RepeatedField<global::WUProtos.Data.Client.ClientCombatMoveType> possibleMoves_ = new pbc::RepeatedField<global::WUProtos.Data.Client.ClientCombatMoveType>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::WUProtos.Data.Client.ClientCombatMoveType> PossibleMoves {
      get { return possibleMoves_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientCombatState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientCombatState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!possibleMoves_.Equals(other.possibleMoves_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= possibleMoves_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      possibleMoves_.WriteTo(output, _repeated_possibleMoves_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += possibleMoves_.CalculateSize(_repeated_possibleMoves_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientCombatState other) {
      if (other == null) {
        return;
      }
      possibleMoves_.Add(other.possibleMoves_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            possibleMoves_.AddEntriesFrom(input, _repeated_possibleMoves_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
