// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Client/ClientFtueVideoQualityMapping.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Client {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Client/ClientFtueVideoQualityMapping.proto</summary>
  public static partial class ClientFtueVideoQualityMappingReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Client/ClientFtueVideoQualityMapping.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientFtueVideoQualityMappingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhXVVByb3Rvcy9EYXRhL0NsaWVudC9DbGllbnRGdHVlVmlkZW9RdWFsaXR5",
            "TWFwcGluZy5wcm90bxIUV1VQcm90b3MuRGF0YS5DbGllbnQihAIKHUNsaWVu",
            "dEZ0dWVWaWRlb1F1YWxpdHlNYXBwaW5nEkwKB21lYXN1cmUYASABKA4yOy5X",
            "VVByb3Rvcy5EYXRhLkNsaWVudC5DbGllbnRGdHVlVmlkZW9RdWFsaXR5TWFw",
            "cGluZy5NZWFzdXJlEhMKC2xvd2VyX2JvdW5kGAIgASgFEhMKC3VwcGVyX2Jv",
            "dW5kGAMgASgFImsKB01lYXN1cmUSFgoSY2FtZXJhX3BpeGVsX3dpZHRoEAAS",
            "FwoTY2FtZXJhX3BpeGVsX2hlaWdodBABEhYKEnNjcmVlbl9waXhlbF93aWR0",
            "aBACEhcKE3NjcmVlbl9waXhlbF9oZWlnaHQQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Client.ClientFtueVideoQualityMapping), global::WUProtos.Data.Client.ClientFtueVideoQualityMapping.Parser, new[]{ "Measure", "LowerBound", "UpperBound" }, null, new[]{ typeof(global::WUProtos.Data.Client.ClientFtueVideoQualityMapping.Types.Measure) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientFtueVideoQualityMapping : pb::IMessage<ClientFtueVideoQualityMapping> {
    private static readonly pb::MessageParser<ClientFtueVideoQualityMapping> _parser = new pb::MessageParser<ClientFtueVideoQualityMapping>(() => new ClientFtueVideoQualityMapping());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientFtueVideoQualityMapping> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Client.ClientFtueVideoQualityMappingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientFtueVideoQualityMapping() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientFtueVideoQualityMapping(ClientFtueVideoQualityMapping other) : this() {
      measure_ = other.measure_;
      lowerBound_ = other.lowerBound_;
      upperBound_ = other.upperBound_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientFtueVideoQualityMapping Clone() {
      return new ClientFtueVideoQualityMapping(this);
    }

    /// <summary>Field number for the "measure" field.</summary>
    public const int MeasureFieldNumber = 1;
    private global::WUProtos.Data.Client.ClientFtueVideoQualityMapping.Types.Measure measure_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.Client.ClientFtueVideoQualityMapping.Types.Measure Measure {
      get { return measure_; }
      set {
        measure_ = value;
      }
    }

    /// <summary>Field number for the "lower_bound" field.</summary>
    public const int LowerBoundFieldNumber = 2;
    private int lowerBound_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LowerBound {
      get { return lowerBound_; }
      set {
        lowerBound_ = value;
      }
    }

    /// <summary>Field number for the "upper_bound" field.</summary>
    public const int UpperBoundFieldNumber = 3;
    private int upperBound_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UpperBound {
      get { return upperBound_; }
      set {
        upperBound_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientFtueVideoQualityMapping);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientFtueVideoQualityMapping other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Measure != other.Measure) return false;
      if (LowerBound != other.LowerBound) return false;
      if (UpperBound != other.UpperBound) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Measure != 0) hash ^= Measure.GetHashCode();
      if (LowerBound != 0) hash ^= LowerBound.GetHashCode();
      if (UpperBound != 0) hash ^= UpperBound.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Measure != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Measure);
      }
      if (LowerBound != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LowerBound);
      }
      if (UpperBound != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(UpperBound);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Measure != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Measure);
      }
      if (LowerBound != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LowerBound);
      }
      if (UpperBound != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpperBound);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientFtueVideoQualityMapping other) {
      if (other == null) {
        return;
      }
      if (other.Measure != 0) {
        Measure = other.Measure;
      }
      if (other.LowerBound != 0) {
        LowerBound = other.LowerBound;
      }
      if (other.UpperBound != 0) {
        UpperBound = other.UpperBound;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Measure = (global::WUProtos.Data.Client.ClientFtueVideoQualityMapping.Types.Measure) input.ReadEnum();
            break;
          }
          case 16: {
            LowerBound = input.ReadInt32();
            break;
          }
          case 24: {
            UpperBound = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ClientFtueVideoQualityMapping message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Measure {
        [pbr::OriginalName("camera_pixel_width")] CameraPixelWidth = 0,
        [pbr::OriginalName("camera_pixel_height")] CameraPixelHeight = 1,
        [pbr::OriginalName("screen_pixel_width")] ScreenPixelWidth = 2,
        [pbr::OriginalName("screen_pixel_height")] ScreenPixelHeight = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
