// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Client/ClientTelemetryOutpostInteract.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Client {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Client/ClientTelemetryOutpostInteract.proto</summary>
  public static partial class ClientTelemetryOutpostInteractReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Client/ClientTelemetryOutpostInteract.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientTelemetryOutpostInteractReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjlXVVByb3Rvcy9EYXRhL0NsaWVudC9DbGllbnRUZWxlbWV0cnlPdXRwb3N0",
            "SW50ZXJhY3QucHJvdG8SFFdVUHJvdG9zLkRhdGEuQ2xpZW50Gh9XVVByb3Rv",
            "cy9EYXRhL1BPSUludGVyYWN0LnByb3RvImcKHkNsaWVudFRlbGVtZXRyeU91",
            "dHBvc3RJbnRlcmFjdBIUCgxvdXRwb3N0X3R5cGUYASABKAkSLwoLY29tbW9u",
            "X2RhdGEYAiABKAsyGi5XVVByb3Rvcy5EYXRhLlBPSUludGVyYWN0YgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Data.POIInteractReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Client.ClientTelemetryOutpostInteract), global::WUProtos.Data.Client.ClientTelemetryOutpostInteract.Parser, new[]{ "OutpostType", "CommonData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientTelemetryOutpostInteract : pb::IMessage<ClientTelemetryOutpostInteract> {
    private static readonly pb::MessageParser<ClientTelemetryOutpostInteract> _parser = new pb::MessageParser<ClientTelemetryOutpostInteract>(() => new ClientTelemetryOutpostInteract());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientTelemetryOutpostInteract> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Client.ClientTelemetryOutpostInteractReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientTelemetryOutpostInteract() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientTelemetryOutpostInteract(ClientTelemetryOutpostInteract other) : this() {
      outpostType_ = other.outpostType_;
      commonData_ = other.commonData_ != null ? other.commonData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientTelemetryOutpostInteract Clone() {
      return new ClientTelemetryOutpostInteract(this);
    }

    /// <summary>Field number for the "outpost_type" field.</summary>
    public const int OutpostTypeFieldNumber = 1;
    private string outpostType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OutpostType {
      get { return outpostType_; }
      set {
        outpostType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "common_data" field.</summary>
    public const int CommonDataFieldNumber = 2;
    private global::WUProtos.Data.POIInteract commonData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Data.POIInteract CommonData {
      get { return commonData_; }
      set {
        commonData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientTelemetryOutpostInteract);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientTelemetryOutpostInteract other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OutpostType != other.OutpostType) return false;
      if (!object.Equals(CommonData, other.CommonData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OutpostType.Length != 0) hash ^= OutpostType.GetHashCode();
      if (commonData_ != null) hash ^= CommonData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OutpostType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(OutpostType);
      }
      if (commonData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(CommonData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OutpostType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OutpostType);
      }
      if (commonData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CommonData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientTelemetryOutpostInteract other) {
      if (other == null) {
        return;
      }
      if (other.OutpostType.Length != 0) {
        OutpostType = other.OutpostType;
      }
      if (other.commonData_ != null) {
        if (commonData_ == null) {
          CommonData = new global::WUProtos.Data.POIInteract();
        }
        CommonData.MergeFrom(other.CommonData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OutpostType = input.ReadString();
            break;
          }
          case 18: {
            if (commonData_ == null) {
              CommonData = new global::WUProtos.Data.POIInteract();
            }
            input.ReadMessage(CommonData);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
