// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WUProtos/Data/Client/ClientEnvironmentTags.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WUProtos.Data.Client {

  /// <summary>Holder for reflection information generated from WUProtos/Data/Client/ClientEnvironmentTags.proto</summary>
  public static partial class ClientEnvironmentTagsReflection {

    #region Descriptor
    /// <summary>File descriptor for WUProtos/Data/Client/ClientEnvironmentTags.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientEnvironmentTagsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjBXVVByb3Rvcy9EYXRhL0NsaWVudC9DbGllbnRFbnZpcm9ubWVudFRhZ3Mu",
            "cHJvdG8SFFdVUHJvdG9zLkRhdGEuQ2xpZW50GiBXVVByb3Rvcy9FbnVtcy9E",
            "YXlOaWdodFRhZy5wcm90bxohV1VQcm90b3MvRW51bXMvTW9vblBoYXNlVGFn",
            "LnByb3RvInkKFUNsaWVudEVudmlyb25tZW50VGFncxIuCglkYXlfbmlnaHQY",
            "ASABKA4yGy5XVVByb3Rvcy5FbnVtcy5EYXlOaWdodFRhZxIwCgptb29uX3Bo",
            "YXNlGAIgASgOMhwuV1VQcm90b3MuRW51bXMuTW9vblBoYXNlVGFnYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WUProtos.Enums.DayNightTagReflection.Descriptor, global::WUProtos.Enums.MoonPhaseTagReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WUProtos.Data.Client.ClientEnvironmentTags), global::WUProtos.Data.Client.ClientEnvironmentTags.Parser, new[]{ "DayNight", "MoonPhase" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClientEnvironmentTags : pb::IMessage<ClientEnvironmentTags> {
    private static readonly pb::MessageParser<ClientEnvironmentTags> _parser = new pb::MessageParser<ClientEnvironmentTags>(() => new ClientEnvironmentTags());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClientEnvironmentTags> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WUProtos.Data.Client.ClientEnvironmentTagsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientEnvironmentTags() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientEnvironmentTags(ClientEnvironmentTags other) : this() {
      dayNight_ = other.dayNight_;
      moonPhase_ = other.moonPhase_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClientEnvironmentTags Clone() {
      return new ClientEnvironmentTags(this);
    }

    /// <summary>Field number for the "day_night" field.</summary>
    public const int DayNightFieldNumber = 1;
    private global::WUProtos.Enums.DayNightTag dayNight_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Enums.DayNightTag DayNight {
      get { return dayNight_; }
      set {
        dayNight_ = value;
      }
    }

    /// <summary>Field number for the "moon_phase" field.</summary>
    public const int MoonPhaseFieldNumber = 2;
    private global::WUProtos.Enums.MoonPhaseTag moonPhase_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::WUProtos.Enums.MoonPhaseTag MoonPhase {
      get { return moonPhase_; }
      set {
        moonPhase_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClientEnvironmentTags);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClientEnvironmentTags other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DayNight != other.DayNight) return false;
      if (MoonPhase != other.MoonPhase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DayNight != 0) hash ^= DayNight.GetHashCode();
      if (MoonPhase != 0) hash ^= MoonPhase.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DayNight != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DayNight);
      }
      if (MoonPhase != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) MoonPhase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DayNight != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DayNight);
      }
      if (MoonPhase != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MoonPhase);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClientEnvironmentTags other) {
      if (other == null) {
        return;
      }
      if (other.DayNight != 0) {
        DayNight = other.DayNight;
      }
      if (other.MoonPhase != 0) {
        MoonPhase = other.MoonPhase;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DayNight = (global::WUProtos.Enums.DayNightTag) input.ReadEnum();
            break;
          }
          case 16: {
            MoonPhase = (global::WUProtos.Enums.MoonPhaseTag) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
